#!/usr/bin/env bash
# This script configures /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8.

sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2\tlocalhost/g' /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/g' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi