#!/usr/bin/env bash
# Configure localhost and facebook.com in the hosts file.
temporary_file=$(mktemp)
trap 'rm -f "$temporary_file"' EXIT
sed 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts |
    sed '/facebook\.com/d' > "$temporary_file"
printf '%s\n' '8.8.8.8 facebook.com' >> "$temporary_file"
cat "$temporary_file" > /etc/hosts
